name: Validate Messages

on:
  push:
    branches: [ 'latest-stable', 'develop' ]
  pull_request:
    branches: [ 'latest-stable', 'develop' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install ResourceBundle
        run: python -m pip install ResourceBundle
      - name: Install yaml
        run: python -m pip install PyYAML
      - name: Run Python script
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            os.system('messages.py')
            
            # An error could occur if:
            # 1. A .properties file is not encode with utf-8
            # 2. A defined plugin in the settings.yml does not exists (the folder) 
            # 3. A defined language in the settings.yml does not exists (the file) 
            # 4. A .properties file has an entry with an incorrect format (e.g. missing '=' sign)
            # 5. A .properties file has a duplicated key
            # 6. A plugin has inconsistent keys among the .properties files (not all files have the same keys)
            # 7. A placeholder was indicated but the '}' is missing
            # 8. A prefix was indicated (means the value contains '${prefix.') but the used prefix does not exist